create extension if not exists "pgcrypto";

create table if not exists public.drawing_exercises (
  id uuid primary key default gen_random_uuid(),
  level text,
  focus text,
  title text not null,
  description text not null,
  difficulty text,
  duration text,
  steps text[] not null default '{}',
  tips text[] not null default '{}',
  focus_points text[] not null default '{}',
  materials text[] not null default '{}',
  step_images text[] not null default '{}',
  metadata jsonb,
  created_at timestamptz not null default now()
);

comment on table public.drawing_exercises is 'Exercises generated by the AI coach and stored for later retrieval.';

alter table public.drawing_exercises enable row level security;

create policy "Public read access" on public.drawing_exercises
  for select
  using (true);

create policy "Service role insert access" on public.drawing_exercises
  for insert
  with check (auth.role() = 'service_role');

create index if not exists drawing_exercises_created_at_idx
  on public.drawing_exercises (created_at desc);
