// This file is automatically generated. Do not edit it directly.
import { createClient, type FunctionInvokeOptions } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID;
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  (SUPABASE_PROJECT_ID ? `https://${SUPABASE_PROJECT_ID}.supabase.co` : undefined);
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const storage = typeof window !== "undefined" ? window.localStorage : undefined;

if (!SUPABASE_URL) {
  throw new Error(
    "Supabase URL non configurée. Définissez VITE_SUPABASE_URL ou VITE_SUPABASE_PROJECT_ID dans le fichier .env.",
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Clé publique Supabase manquante. Définissez VITE_SUPABASE_PUBLISHABLE_KEY dans le fichier .env.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

export const invokeEdgeFunction = async <T = unknown>(
  functionName: string,
  options: FunctionInvokeOptions = {},
) => {
  const { headers, ...rest } = options;

  return supabase.functions.invoke<T>(functionName, {
    ...rest,
    headers: {
      Authorization: `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
      ...headers,
    },
  });
};
